class Constants:
    """
        H is derived by considering the fractional parts of random points on the curves
        9x^2 - 4y^2 = 36 and x^2 + y^2 = 256
    """

    H = [
        0xf851b92da3f6f800, 0x783ddba1db8f3000, 0xf829964478e0a000,
        0x7814e5df26e76800, 0xf7ffc7194876e800, 0x77ea367629efc800,
        0xdb3d742c2655b000, 0xffeb4d505ccd6800, 0x19bc5a9d91f59100,
        0xffad357700402000, 0xfdfa974e88444000, 0xb417e9e3dec6b000
    ]

    """
        The values of K are generated by offsetting the unsigned 64 bit value 
        of the Permitivity of Free Space, ε₀ = 8.8541878128e-12
    """

    K = [
        0xa5a5a5a5ac199edd, 0x4b4b4b4b42f77032, 0xf0f0f0f0f94ccb97, 0x969696969f2aadec,
        0x3c3c3c3c35800741, 0xe1e1e1e1e85ddaa6, 0x878787878e3bbcfb, 0x2d2d2d2d24911650,
        0xd2d2d2d2db6ee9b5, 0x7878787871c4430a, 0x1e1e1e1e17a2256f, 0xc3c3c3c3ca7ff8c4,
        0x6969696960d55219, 0xf0f0f0f06b3347e, 0xb4b4b4b4bd088fd3, 0x5a5a5a5a53e66128,
        0xfffffffff643c48d, 0xa5a5a5a5ac199ee2, 0x4b4b4b4b42f77047, 0xf0f0f0f0f94ccb9c,
        0x969696969f2aadf1, 0x3c3c3c3c35800756, 0xe1e1e1e1e85ddaab, 0x878787878e3bbc00,
        0x2d2d2d2d24911665, 0xd2d2d2d2db6ee9ba, 0x7878787871c4431f, 0x1e1e1e1e17a22574,
        0xc3c3c3c3ca7ff8c9, 0x6969696960d5522e, 0xf0f0f0f06b33583, 0xb4b4b4b4bd088fd8,
        0x5a5a5a5a53e6613d, 0xfffffffff643c492, 0xa5a5a5a5ac199ef7, 0x4b4b4b4b42f7704c,
        0xf0f0f0f0f94ccba1, 0x969696969f2aad06, 0x3c3c3c3c3580075b, 0xe1e1e1e1e85ddab0,
        0x878787878e3bbc15, 0x2d2d2d2d2491166a, 0xd2d2d2d2db6ee9cf, 0x7878787871c44324,
        0x1e1e1e1e17a22579, 0xc3c3c3c3ca7ff8de, 0x6969696960d55233, 0xf0f0f0f06b33588,
        0xb4b4b4b4bd088fed, 0x5a5a5a5a53e66142, 0xfffffffff643c4a7, 0xa5a5a5a5ac199efc,
        0x4b4b4b4b42f77051, 0xf0f0f0f0f94ccbb6, 0x969696969f2aad0b, 0x3c3c3c3c35800760,
        0xe1e1e1e1e85ddac5, 0x878787878e3bbc1a, 0x2d2d2d2d2491167f, 0xd2d2d2d2db6ee9d4,
        0x7878787871c44329, 0x1e1e1e1e17a2268e, 0xc3c3c3c3ca7ff8e3, 0x6969696960d55238,
        0xf0f0f0f06b3359d, 0xb4b4b4b4bd088ff2, 0x5a5a5a5a53e66157, 0xfffffffff643c4ac,
        0xa5a5a5a5ac199e01, 0x4b4b4b4b42f77066, 0xf0f0f0f0f94ccbbb, 0x969696969f2aad10,
        0x3c3c3c3c35800775, 0xe1e1e1e1e85ddaca, 0x878787878e3bbc2f, 0x2d2d2d2d24911784,
        0xd2d2d2d2db6ee9d9, 0x7878787871c4433e, 0x1e1e1e1e17a22693, 0xc3c3c3c3ca7ff8e8,
        0x6969696960d5524d, 0xf0f0f0f06b335a2, 0xb4b4b4b4bd088f07, 0x5a5a5a5a53e6615c,
        0xfffffffff643c4b1, 0xa5a5a5a5ac199e16, 0x4b4b4b4b42f7706b, 0xf0f0f0f0f94ccbc0
    ]
